# Generated by Django 3.2.8 on 2021-10-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
