# Generated by Django 3.2.8 on 2021-10-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pollanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollanswer',
            name='users',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
