# Generated by Django 3.2.8 on 2021-10-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pollanswer_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='author',
        ),
    ]
