# Generated by Django 3.2.8 on 2021-10-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_poll_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollanswer',
            name='poll',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
