# Generated by Django 3.2.8 on 2021-10-15 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_poll_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollanswer',
            name='el',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.poll'),
        ),
    ]
