# Generated by Django 3.2.8 on 2021-10-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_pollanswer_el'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollanswer',
            name='users',
        ),
        migrations.AlterField(
            model_name='pollanswer',
            name='poll',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('answer', models.IntegerField()),
                ('value', models.CharField(max_length=40, null=True)),
                ('el', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.pollanswer')),
            ],
        ),
    ]
